### ISSUE TITLE
Why did not implement "Graph Contrastive Learning with Adaptive Augmentation"

### ISSUE THREAD

**Issue by mhadnanali** [PyGCL/PyGCL#30]
I am reading your paper "Graph Contrastive Learning with Adaptive Augmentation" and want to compare its results with my work, but I see you did not implement this paper in PyGCL. 
Any specific reason?

**Comment by Linyxus** [comment]
Hey mhadnanali. Thank you for your interest in PyGCL.

reg. GCA implementation: the implementation of GCA is on our schedule. We are currently trying to make PyGCL easier to use in the next milestone. After this, we will reproduce more models and add them into the library. So please stay tuned. :D

reg. difference between implementation of GRACE in original paper and in PyGCL: they should be functionally equivalent, and they actually follow the same settings (contrastive learning and then employ a LR classifier to evaluate embedding quality). It should be enough to use the implementation in PyGCL.

**Comment by Linyxus** [comment]
Hey! Thank you for your interests in our work. We have added GCA in PyGCL (#47).
