### ISSUE TITLE
error:could noy find a version that satisfies the requirement PyGCL

### ISSUE THREAD

**Issue by jingzhengli** [PyGCL/PyGCL#45]

**Comment by jingzhengli** [comment]
Thanks for sharing the great code. but I encount an issue when "pip install PyGCL"

ERROR:could not find a version that satisfies the requirement PyGCL
ERROR:No matching distribution found for PyGCL

what should i do?

**Comment by jingzhengli** [comment]
> Thanks for sharing the great code. but I encount an issue when "pip install PyGCL"
> 
> **ERROR:could not find a version that satisfies the requirement PyGCL (from version:none) ERROR:No matching distribution found for PyGCL**
> 
> This issue has not yet been resolved. what should i do?

sorry, the reason is that my python version is 3.7...

**Comment by SXKDZ** [comment]
Glad to see the problem solved 😃 !
