### ISSUE TITLE
关于增强方法Identity()

### ISSUE THREAD

**Issue by codenoob1997** [PyGCL/PyGCL#52]
`
class Identity(Augmentor):
    def __init__(self):
        super(Identity, self).__init__()

    def augment(self, g: Graph) -> Graph:
        return g
`
该方法返回一个原图，请问一下为什么这个原图被视为一个ego-graph呢？  
谢谢解答

**Comment by SXKDZ** [comment]
感谢关注。考虑l层GCN作为encoder，此时原图augmentation相当于提取l-ego graph。
