### ISSUE TITLE
关于训练数据划分

### ISSUE THREAD

**Issue by ZhaoYuTJPU** [PyGCL/PyGCL#53]
![image](https://user-images.githubusercontent.com/86563793/180724257-011dc069-09fa-4ee8-84df-aa2007eb86ae.png)
你好，你们的GCL.eval中，关于训练集和测试集的划分部分，我认为我标红的部分，即val和test是否应当变换顺序？

**Comment by SXKDZ** [comment]
感谢关注，我们已经在develop分支修复了这个问题
