### ISSUE TITLE
关于Develop分支

### ISSUE THREAD

**Issue by ZhaoYuTJPU** [PyGCL/PyGCL#55]
您好，我看到你们更新了新的Develop分支，请问我该如何将我的PyGCL更新为Develop分支中的新版本呢？

**Comment by Linyxus** [comment]
您好，`develop`分支仍在开发中，在合并入`main`分支后将发布新的`pypi`包。若你希望在现在就使用`develop`分支上的代码，可以`git clone`我们的仓库至本地，随后在仓库的目录内执行：
```bash
pip install -e ./
```
