### ISSUE TITLE
Why there is no batch size implementation 

### ISSUE THREAD

**Issue by mhadnanali** [PyGCL/PyGCL#59]
Hello, in your implementation of GRACE i could not find the batch size option, I am unable to execute GRACE with DBLP and PubMed on 24 GB GPU. 

Any solution or suggestion for that?

**Comment by SXKDZ** [comment]
Hi, thanks for your interests on our work. On node-level tasks, the dataset contains only one (possibly large) graph. Therefore there is no parameter for batch size (=1). You can do subsampling to reduce memory consumption as suggested in [this work](https://openreview.net/forum?id=0UXT6PpRpW).
