### ISSUE TITLE
About different results running the same code

### ISSUE THREAD

**Issue by zhandand** [PyGCL/PyGCL#60]
Though I have fix the seed, the results after running the same code are different. Do u have any ideas about that?
`    random.seed(0)

    np.random.seed(0)
    torch.manual_seed(0)
    torch.cuda.manual_seed_all(0)    
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False`

**Comment by zhandand** [comment]
I am wondering if [this](https://github.com/pyg-team/pytorch_geometric/issues/92) could answer my question.

**Comment by SXKDZ** [comment]
Thanks for your interests. Your referred information is correct. That has something to do with PyG's side. You need to convert the sparse adjacency matrix to `adj_t` type. Please refer to [their tutorial](https://pytorch.org/docs/stable/notes/randomness.html) on the randomness in experiments.
