### ISSUE TITLE
Eval.py get_split error?

### ISSUE THREAD

**Issue by ventr1c** [PyGCL/PyGCL#65]
Hi,

I found a issue of get_split() in eval.py. I think the index of valid and test should be switched. For example, the correct one would be:

def get_split(num_samples: int, train_ratio: float = 0.1, test_ratio: float = 0.8):
    assert train_ratio + test_ratio < 1
    train_size = int(num_samples * train_ratio)
    test_size = int(num_samples * test_ratio)
    indices = torch.randperm(num_samples)
    return {
        'train': indices[:train_size],
        'test': indices[train_size: test_size + train_size],
        'valid': indices[test_size + train_size:]
    }

Thanks!

**Comment by SXKDZ** [comment]
Thank you for your question! Actually we have fixed this problem in the [develop](https://github.com/PyGCL/PyGCL/blob/develop/GCL/eval/split.py) branch.
