### ISSUE TITLE
Can PyGCL used in torch_geometric.data.HeteroData 

### ISSUE THREAD

**Issue by xiachenrui** [PyGCL/PyGCL#66]
Hi, the PyGCL is really useful. I want to know if it is possible to extend it to `torch_geometric.data.HeteroData`. I scanned the code and guessed it can not yet. Do you plan to do this in the future?

**Comment by SXKDZ** [comment]
Unfortunately no. I'm shifting my research from graph models to other domains. Thus I have a very limited time for maintaining this project.

**Comment by xiachenrui** [comment]
Thanks
